name: Docker Image CI

on:
  push:
    branches: [ "build" ]

  pull_request:
    branches: [ "build" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tradesys:$(date +%s) --tag tradesys:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push tradesys:$(date +%s)

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH to VPS and Run Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop tradesys:latest || true && docker rm tradesys:latest || true  && docker rmi tradesys:latest || true
          docker login
          docker pull tradesys:latest
          docker run -d --name trade_sys --network main-proxy_default --restart on-failure:5 tradesys:latest
    
    

    
