name: Docker Image CI

on:
#  push:
#    branches: [ "build" ]

  pull_request:
    branches: [ "build" ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ vars.IMG_NAME }}:${{ steps.vars.outputs.sha_short }} -t ${{ vars.IMG_NAME }}:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push version image
      run: docker push ${{ vars.IMG_NAME }}:${{ steps.vars.outputs.sha_short }}

    - name: Push latest image
      run: docker push ${{ vars.IMG_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to VPS and Run Docker Container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop trade_sys || true && docker rm trade_sys || true  && docker rmi ${{ secrets.IMG_NAME }}:latest || true
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull ${{ vars.IMG_NAME }}:latest
          docker run -d --name trade_sys --network main-proxy_default --restart on-failure:5 ${{ vars.IMG_NAME }}:latest